### ISSUE TITLE
Verify Cubiomes Viewer

### ISSUE THREAD

**Issue by JakobDev** [flathub/com.github.cubitect.cubiomes-viewer#7]
Flathub has now a new Website which includes new features such as Verification. Verification means, that the Flatpak is a official one that is supported by the Developer. You should verify Cubiomes Viewer. Just go to [flathub.org](https://flathub.org), log in with your GitHub Account, open the Developer Settings and select "Login Provider verfication".

**Comment by Cubitect** [comment]
Done
